# Site settings
title: Ooma Office for WeWork Support
email: support@ooma.com
description: "Support site for Ooma Office for WeWork"
url: "http://wework-support.ooma.com"
# url: "http://ooma-web.github.io/wework-support"
twitter_username: ooma
github_username:  ooma-web
permalink: /:categories/:title
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown

office_link:
  us: "http://office.ooma.com"
  fr: "http://office.ooma.fr"
      